### ISSUE TITLE
Actividad 3, Hernández Matra Jorge Luis, grupo:1BS

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-JORGELUIS2266#1]
[HERNANDEZ MATRA JORGE LUIS-METODO CIENTIFICO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-JORGELUIS2266/files/9470126/HERNANDEZ.MATRA.JORGE.LUIS-METODO.CIENTIFICO.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by josealfredo79** [comment]
Calificacion 13

**Comment by josealfredo79** [comment]
Faltan las referencias

**Comment by josealfredo79** [comment]
Revisado..
